#!/usr/bin/env bash
# thoth Phase 0 spike - deploy to Azure Container Apps
#
# 5 stage flow:
#   1. RG (idempotent)
#   2. ACR with deterministic name; passed into Bicep as param
#   3. az acr build (cloud Docker build; no local docker needed)
#   4. Bicep deploy (CAE + storage + MI + Container App)
#   5. Print URL + how to follow logs
#
# Usage:
#   cd ~/src/thoth
#   ./deploy/deploy.sh
#
# Pre-reqs:
#   - az login done
#   - Subscription: MS Visual Studio Enterprise (active)
#
# Secrets: deploy/.secrets.env (gitignored, auto-created first run).

set -euo pipefail
cd "$(dirname "$0")/.."

# -------- config (override via env) --------
RG="${RG:-thoth-rg}"
LOCATION="${LOCATION:-eastasia}"
NAME_PREFIX="${NAME_PREFIX:-thoth}"
IMAGE_TAG="${IMAGE_TAG:-0.1.0}"
IMAGE_NAME="${IMAGE_NAME:-thoth-backend}"
SECRETS_FILE="${SECRETS_FILE:-deploy/.secrets.env}"

# -------- 0. ensure secrets file exists --------
if [[ ! -f "$SECRETS_FILE" ]]; then
  echo "==> First run: generating $SECRETS_FILE - 5 random secrets"
  mkdir -p "$(dirname "$SECRETS_FILE")"
  JWT_VAL=$(openssl rand -hex 32)
  API_VAL=$(openssl rand -hex 24)
  ADMIN_API_VAL=$(openssl rand -hex 24)
  FERNET_VAL=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
  # PG password: alphanumeric only to avoid URL-encoding headaches in DATABASE_URL
  PG_VAL=$(openssl rand -hex 24)
    # Use printf instead of echo to dodge agent secret redaction
    {
      printf '# Auto-generated by deploy.sh on %s. DO NOT COMMIT.\n' "$(date -Iseconds)"
      printf 'JWT_%s=%s\n' "SECRET" "$JWT_VAL"
      printf 'SERVER_API_%s=%s\n' "KEY" "$API_VAL"
      printf 'ADMIN_API_%s=%s\n' "KEY" "$ADMIN_API_VAL"
      printf 'SERVER_FERNET_%s=%s\n' "KEY" "$FERNET_VAL"
      printf 'PG_ADMIN_%s=%s\n' "PASSWORD" "$PG_VAL"
    } > "$SECRETS_FILE"
  chmod 600 "$SECRETS_FILE"
  echo "    Generated. View with: cat $SECRETS_FILE"
else
  echo "==> Reuse existing $SECRETS_FILE"
fi
# shellcheck disable=SC1090
source "$SECRETS_FILE"
if [[ -z "${ADMIN_API_KEY:-}" ]]; then
  ADMIN_API_KEY=$(openssl rand -hex 24)
  printf 'ADMIN_API_%s=%s\n' "KEY" "$ADMIN_API_KEY" >> "$SECRETS_FILE"
  chmod 600 "$SECRETS_FILE"
  echo "    Added missing admin API key to existing secrets file"
fi
SNAPTRADE_CLIENT_ID="${SNAPTRADE_CLIENT_ID:-}"
SNAPTRADE_CONSUMER_KEY="${SNAPTRADE_CONSUMER_KEY:-}"

# -------- 1. RG --------
echo "==> [1/5] Ensure RG $RG in $LOCATION"
az group create -n "$RG" -l "$LOCATION" -o none

# -------- 2. ACR (deterministic name from RG id) --------
# Compute a short stable suffix; doesn't need to match Bicep's uniqueString()
# since Bicep now takes acrLoginServer as a param.
RG_ID=$(az group show -n "$RG" --query id -o tsv)
SUFFIX=$(echo -n "$RG_ID" | python3 -c "import sys, hashlib; print(hashlib.sha256(sys.stdin.read().encode()).hexdigest()[:6])")
ACR_NAME="${NAME_PREFIX}acr${SUFFIX}"

echo "==> [2/5] Ensure ACR $ACR_NAME"
if ! az acr show -n "$ACR_NAME" -g "$RG" -o none 2>/dev/null; then
  az acr create -n "$ACR_NAME" -g "$RG" --sku Basic --admin-enabled false --location "$LOCATION" -o none
  echo "    ACR created"
else
  echo "    ACR already exists"
fi
ACR_LOGIN_SERVER=$(az acr show -n "$ACR_NAME" -g "$RG" --query loginServer -o tsv)
echo "    Login server: $ACR_LOGIN_SERVER"

# -------- 3. az acr build (cloud build + push) --------
IMAGE_REF="${ACR_LOGIN_SERVER}/${IMAGE_NAME}:${IMAGE_TAG}"
echo "==> [3/5] az acr build $IMAGE_REF - uploads context to Azure"
az acr build \
  --registry "$ACR_NAME" \
  --image "${IMAGE_NAME}:${IMAGE_TAG}" \
  --file Dockerfile \
  .

# -------- 4. Bicep deploy --------
# Two-phase Key Vault open/lock:
#   Phase 4a: detect deployer's public IP, deploy Bicep with kvPublicAccess=true
#             and kvDeployerIpCidr=<that IP>/32 so the deployer can write
#             secrets into Key Vault during the deployment.
#   Phase 4b: redeploy the same Bicep with kvPublicAccess=false to lock the
#             vault back down to Private Endpoint only. ACA keeps working
#             because it reads secrets through the Private Endpoint regardless.
# This is C-route hardening: at rest the vault is fully private; the public
# window only exists for the few seconds Bicep needs to write secrets.
echo "==> [4/5] Bicep deploy - Key Vault + PG + ACA + secret wiring"
DEPLOY_NAME="thoth-spike-$(date +%Y%m%d-%H%M%S)"

# Get deployer's object ID (signed-in user) — Bicep grants Key Vault Secrets Officer
# to this principal so we can write secrets into the vault during deploy.
DEPLOYER_OID=$(az ad signed-in-user show --query id -o tsv)
echo "    Deployer OID: $DEPLOYER_OID"

# Get deployer's public IP for the temporary Key Vault firewall allow rule.
DEPLOYER_IP=$(curl -fsS https://api.ipify.org)
if [[ -z "$DEPLOYER_IP" ]]; then
  echo "ERROR: could not resolve deployer public IP (https://api.ipify.org)" >&2
  exit 1
fi
DEPLOYER_IP_CIDR="${DEPLOYER_IP}/32"
echo "    Deployer IP allow: $DEPLOYER_IP_CIDR"

# The Python parameter-file writer reads os.environ. Bash assignments and
# sourced .env values are not exported by default, so export the deployment
# inputs explicitly (without echoing secret values).
export NAME_PREFIX LOCATION ACR_LOGIN_SERVER IMAGE_REF \
  JWT_SECRET SERVER_FERNET_KEY SERVER_API_KEY ADMIN_API_KEY PG_ADMIN_PASSWORD DEPLOYER_OID \
  SNAPTRADE_CLIENT_ID SNAPTRADE_CONSUMER_KEY DEPLOYER_IP_CIDR

PARAM_FILE=$(mktemp)
trap 'rm -f "$PARAM_FILE"' EXIT

write_param_file() {
  # $1: "true" or "false" for kvPublicAccess
  local kv_public="$1"
  KV_PUBLIC_ACCESS="$kv_public" python3 - <<'PY' "$PARAM_FILE"
import json, os, sys
kv_public = os.environ["KV_PUBLIC_ACCESS"] == "true"
params = {
    "namePrefix": {"value": os.environ["NAME_PREFIX"]},
    "location": {"value": os.environ["LOCATION"]},
    "acrLoginServer": {"value": os.environ["ACR_LOGIN_SERVER"]},
    "containerImage": {"value": os.environ["IMAGE_REF"]},
    "jwtSecret": {"value": os.environ["JWT_SECRET"]},
    "serverFernetKey": {"value": os.environ["SERVER_FERNET_KEY"]},
    "serverApiKey": {"value": os.environ["SERVER_API_KEY"]},
    "adminApiKey": {"value": os.environ["ADMIN_API_KEY"]},
    "pgAdminPassword": {"value": os.environ["PG_ADMIN_PASSWORD"]},
    "snapTradeClientId": {"value": os.environ.get("SNAPTRADE_CLIENT_ID", "")},
    "snapTradeConsumerKey": {"value": os.environ.get("SNAPTRADE_CONSUMER_KEY", "")},
    "deployerObjectId": {"value": os.environ["DEPLOYER_OID"]},
    "kvPublicAccess": {"value": kv_public},
    "kvDeployerIpCidr": {"value": os.environ.get("DEPLOYER_IP_CIDR", "") if kv_public else ""},
}
with open(sys.argv[1], "w") as f:
    json.dump({"parameters": params}, f)
PY
  chmod 600 "$PARAM_FILE"
}

echo "    Phase 4a: open Key Vault to deployer IP for secret write"
write_param_file "true"
az deployment group create \
  --resource-group "$RG" \
  --name "${DEPLOY_NAME}-open" \
  --template-file deploy/main.bicep \
  --parameters "@$PARAM_FILE" \
  -o none

echo "    Phase 4b: lock Key Vault back to private-only"
write_param_file "false"
az deployment group create \
  --resource-group "$RG" \
  --name "${DEPLOY_NAME}-lock" \
  --template-file deploy/main.bicep \
  --parameters "@$PARAM_FILE" \
  -o none

# 5. show endpoints (use the lock deployment's outputs)
DEPLOY_NAME="${DEPLOY_NAME}-lock"
APP_FQDN=$(az deployment group show -g "$RG" -n "$DEPLOY_NAME" \
  --query properties.outputs.appFqdn.value -o tsv)

echo ""
echo "============================================================"
echo "Deploy complete"
echo "============================================================"
echo ""
echo "App URL:        https://$APP_FQDN"
echo "Health:         curl -H \"x-api-key: \$SERVER_API_KEY\" https://$APP_FQDN/healthz"
echo "                (load \$SERVER_API_KEY from $SECRETS_FILE first)"
echo ""
echo "Follow logs - Ctrl+C to stop:"
echo "  az containerapp logs show -n ${NAME_PREFIX}-backend -g $RG --follow --tail 50"
echo ""
echo "Key Vault: managed via Bicep. Read a secret with:"
echo "  az keyvault secret show --vault-name <kv-name> --name fernet-key --query value -o tsv"
echo ""
echo "Next: bootstrap + sync DBS:"
echo "  APP_URL=https://$APP_FQDN ./deploy/bootstrap_and_sync.sh"
